#
# API Deployment
#

# Nginx Config Map
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-api-conf
  labels:
    app: api
    tier: backend
data:
  proxy.html: |
    <!DOCTYPE HTML>
    <script src="//cdn.rawgit.com/jpillora/xdomain/0.6.17/dist/xdomain.min.js"></script>
    <script>
      xdomain.masters({
        "http://thisissoon.fm": "*"
      });
    </script>
  api.conf: |
    server {
        listen 80;
        location =/proxy.html {
            alias /etc/nginx/conf.d/proxy.html;
        }
        location / {
            proxy_pass          http://localhost:5000;
            proxy_set_header    Host            $host;
            proxy_set_header    X-Real-IP       $remote_addr;
            proxy_set_header    X-Forwarded-for $remote_addr;
        }
    }
---
# API Environment Variable Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-env-config
  labels:
    app: api
    tier: backend
data:
  REDIS_HOST: redis:6379
  SQLALCHEMY_DB_HOST: cloudsql.default
  CELERY_BROKER_URL: redis://redis:6379/0
  URL_PREFIX: /api
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: api
    tier: backend
---
# API Deployment
# Runs Nginx / UWSGI and Celery Workers
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      # Volumes
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-api-conf
      # Containers
      containers:
      # Nginx Container
      - name: nginx
        image: gcr.io/soon-fm-production/nginx:1.10.3
        resources:
          requests:
            memory: "10Mi"
            cpu: 0
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
        ports:
        - containerPort: 80
      # # Python API Application
      - name: api
        image: gcr.io/soon-fm-production/api:$TAG
        resources:
          requests:
            memory: "60Mi"
            cpu: 0
        envFrom:
          - configMapRef:
              name: api-env-config
        env:
          - name: SPOTIFY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: spotify
                key: id
          - name: SPOTIFY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: spotify
                key: secret
          - name: CORS_ACA_ORIGIN
            valueFrom:
              secretKeyRef:
                name: api-cors
                key: origin
          - name: ECHONEST_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-echonest
                key: key
          - name: SQLALCHEMY_DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-api-credentials
                key: username
          - name: SQLALCHEMY_DB_PASS
            valueFrom:
              secretKeyRef:
                name: cloudsql-api-credentials
                key: password
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: api-google-oauth
                key: id
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: api-google-oauth
                key: secret
          - name: GOOGLE_REDIRECT_URI
            valueFrom:
              secretKeyRef:
                name: api-google-oauth
                key: redirect
      # Celery Worker
      - name: celery-worker
        image: gcr.io/soon-fm-production/api:$TAG
        resources:
          requests:
            memory: "50Mi"
            cpu: 0
        command:
          - celery
          - -A
          - fm.tasks.app
          - -l
          - info
          - -c
          - '1'
          - worker
        envFrom:
          - configMapRef:
              name: api-env-config
        env:
          - name: C_FORCE_ROOT
            value: "True"
          - name: SPOTIFY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: spotify
                key: id
          - name: SPOTIFY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: spotify
                key: secret
          - name: ECHONEST_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-echonest
                key: key
          - name: SQLALCHEMY_DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-api-credentials
                key: username
          - name: SQLALCHEMY_DB_PASS
            valueFrom:
              secretKeyRef:
                name: cloudsql-api-credentials
                key: password
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: api-google-oauth
                key: id
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: api-google-oauth
                key: secret
          - name: GOOGLE_REDIRECT_URI
            valueFrom:
              secretKeyRef:
                name: api-google-oauth
                key: redirect
---
# Event Listener
# We only ever want to run 1 of these
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-eventlistener
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-eventlistener
        tier: backend
    spec:
      # Containers
      containers:
      - name: api
        image: gcr.io/soon-fm-production/api:$TAG
        resources:
          requests:
            memory: "70Mi"
            cpu: 0
        command:
          - python
          - ./manage.py
          - runeventlistener
        envFrom:
          - configMapRef:
              name: api-env-config
        env:
          - name: SPOTIFY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: spotify
                key: id
          - name: SPOTIFY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: spotify
                key: secret
          - name: ECHONEST_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-echonest
                key: key
          - name: SQLALCHEMY_DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-api-credentials
                key: username
          - name: SQLALCHEMY_DB_PASS
            valueFrom:
              secretKeyRef:
                name: cloudsql-api-credentials
                key: password
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: api-google-oauth
                key: id
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: api-google-oauth
                key: secret
          - name: GOOGLE_REDIRECT_URI
            valueFrom:
              secretKeyRef:
                name: api-google-oauth
                key: redirect
---
# Migration Job
apiVersion: batch/v1
kind: Job
metadata:
  name: api-db-upgrade-$TAG
spec:
  template:
    metadata:
      labels:
        app: api-dbupgrade
        tier: backend
    spec:
      restartPolicy: Never
      containers:
      - name: dbupgrade
        image: gcr.io/soon-fm-production/api:$TAG
        command:
          - python
          - ./manage.py
          - db
          - upgrade
        envFrom:
          - configMapRef:
              name: api-env-config
        env:
          - name: SQLALCHEMY_DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-api-credentials
                key: username
          - name: SQLALCHEMY_DB_PASS
            valueFrom:
              secretKeyRef:
                name: cloudsql-api-credentials
                key: password
