"""Genre Artist Association

Revision ID: 18a9779b6cc1
Revises: de29e20a272
Create Date: 2015-04-17 14:57:41.825041

"""

# revision identifiers, used by Alembic.
revision = '18a9779b6cc1'
down_revision = 'de29e20a272'

import fm  # noqa
import sqlalchemy as sa  # noqa

from alembic import op  # noqa
from fm.ext import db  # noqa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_genre',
    sa.Column('created', fm.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated', fm.db.types.UTCDateTime(), nullable=False),
    sa.Column('artist_id', postgresql.UUID(), nullable=False),
    sa.Column('grenre_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['grenre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'grenre_id')
    )
    op.create_index(op.f('ix_artist_genre_artist_id'), 'artist_genre', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artist_genre_created'), 'artist_genre', ['created'], unique=False)
    op.create_index(op.f('ix_artist_genre_grenre_id'), 'artist_genre', ['grenre_id'], unique=False)
    op.create_index(op.f('ix_artist_genre_updated'), 'artist_genre', ['updated'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_genre_updated'), table_name='artist_genre')
    op.drop_index(op.f('ix_artist_genre_grenre_id'), table_name='artist_genre')
    op.drop_index(op.f('ix_artist_genre_created'), table_name='artist_genre')
    op.drop_index(op.f('ix_artist_genre_artist_id'), table_name='artist_genre')
    op.drop_table('artist_genre')
    ### end Alembic commands ###
