"""Initial Spotify Tables

Revision ID: 219d09e1a415
Revises: None
Create Date: 2015-03-02 15:19:53.409121

"""

# revision identifiers, used by Alembic.
revision = '219d09e1a415'
down_revision = None

from alembic import op  # noqa
import sqlalchemy as sa  # noqa
import fm  # noqa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('created', fm.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated', fm.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('spotify_id', sa.Unicode(length=128), nullable=False),
    sa.Column('name', sa.Unicode(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_created'), 'artist', ['created'], unique=False)
    op.create_index(op.f('ix_artist_spotify_id'), 'artist', ['spotify_id'], unique=True)
    op.create_index(op.f('ix_artist_updated'), 'artist', ['updated'], unique=False)
    op.create_table('album',
    sa.Column('created', fm.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated', fm.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('spotify_id', sa.Unicode(length=129), nullable=False),
    sa.Column('name', sa.Unicode(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_created'), 'album', ['created'], unique=False)
    op.create_index(op.f('ix_album_spotify_id'), 'album', ['spotify_id'], unique=True)
    op.create_index(op.f('ix_album_updated'), 'album', ['updated'], unique=False)
    op.create_table('artist_album',
    sa.Column('created', fm.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated', fm.db.types.UTCDateTime(), nullable=False),
    sa.Column('artist_id', postgresql.UUID(), nullable=False),
    sa.Column('album_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'album_id')
    )
    op.create_index(op.f('ix_artist_album_album_id'), 'artist_album', ['album_id'], unique=False)
    op.create_index(op.f('ix_artist_album_artist_id'), 'artist_album', ['artist_id'], unique=False)
    op.create_index(op.f('ix_artist_album_created'), 'artist_album', ['created'], unique=False)
    op.create_index(op.f('ix_artist_album_updated'), 'artist_album', ['updated'], unique=False)
    op.create_table('track',
    sa.Column('created', fm.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated', fm.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('spotify_id', sa.Unicode(length=129), nullable=False),
    sa.Column('album_id', postgresql.UUID(), nullable=False),
    sa.Column('name', sa.Unicode(length=128), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_album_id'), 'track', ['album_id'], unique=False)
    op.create_index(op.f('ix_track_created'), 'track', ['created'], unique=False)
    op.create_index(op.f('ix_track_spotify_id'), 'track', ['spotify_id'], unique=True)
    op.create_index(op.f('ix_track_updated'), 'track', ['updated'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_updated'), table_name='track')
    op.drop_index(op.f('ix_track_spotify_id'), table_name='track')
    op.drop_index(op.f('ix_track_created'), table_name='track')
    op.drop_index(op.f('ix_track_album_id'), table_name='track')
    op.drop_table('track')
    op.drop_index(op.f('ix_artist_album_updated'), table_name='artist_album')
    op.drop_index(op.f('ix_artist_album_created'), table_name='artist_album')
    op.drop_index(op.f('ix_artist_album_artist_id'), table_name='artist_album')
    op.drop_index(op.f('ix_artist_album_album_id'), table_name='artist_album')
    op.drop_table('artist_album')
    op.drop_index(op.f('ix_album_updated'), table_name='album')
    op.drop_index(op.f('ix_album_spotify_id'), table_name='album')
    op.drop_index(op.f('ix_album_created'), table_name='album')
    op.drop_table('album')
    op.drop_index(op.f('ix_artist_updated'), table_name='artist')
    op.drop_index(op.f('ix_artist_spotify_id'), table_name='artist')
    op.drop_index(op.f('ix_artist_created'), table_name='artist')
    op.drop_table('artist')
    ### end Alembic commands ###
