"""OAuth2 Credential Storage

Revision ID: 346114c5f61a
Revises: 5af293f26813
Create Date: 2015-03-06 14:56:54.257106

"""

# revision identifiers, used by Alembic.
revision = '346114c5f61a'
down_revision = '5af293f26813'

from alembic import op  # noqa
import sqlalchemy as sa  # noqa
import fm  # noqa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oauth2_credentials', postgresql.JSON(), nullable=False))
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index('ix_user_token', 'user', ['token'], unique=False)
    op.drop_column('user', 'oauth2_credentials')
    ### end Alembic commands ###
