"""New Playlist History Model

Revision ID: 3da945eb68a1
Revises: 491f96ede5d0
Create Date: 2015-03-23 12:13:18.582809

"""

# revision identifiers, used by Alembic.
revision = '3da945eb68a1'
down_revision = '346114c5f61a'

# Third Pary Libs
import sqlalchemy as sa  # noqa
from alembic import op  # noqa
from sqlalchemy.dialects import postgresql

# First Party Libs
import fm  # noqa
from fm.ext import db  # noqa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_history',
    sa.Column('created', fm.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated', fm.db.types.UTCDateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('track_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_history_created'), 'playlist_history', ['created'], unique=False)
    op.create_index(op.f('ix_playlist_history_track_id'), 'playlist_history', ['track_id'], unique=False)
    op.create_index(op.f('ix_playlist_history_updated'), 'playlist_history', ['updated'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_history_updated'), table_name='playlist_history')
    op.drop_index(op.f('ix_playlist_history_track_id'), table_name='playlist_history')
    op.drop_index(op.f('ix_playlist_history_created'), table_name='playlist_history')
    op.drop_table('playlist_history')
    ### end Alembic commands ###
