"""Add plays field to Track model

Revision ID: 491f96ede5d0
Revises: 8778ad8a7ab
Create Date: 2015-03-17 18:59:00.363547

"""

# revision identifiers, used by Alembic.
revision = '491f96ede5d0'
down_revision = '8778ad8a7ab'
# Third Party Libs
import sqlalchemy as sa  # noqa
from alembic import op  # noqa

# First Party Libs
import fm  # noqa
from fm.ext import db  # noqa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('play_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_track_play_count'), 'track', ['play_count'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_play_count'), table_name='track')
    op.drop_column('track', 'play_count')
    ### end Alembic commands ###
