"""add audio_summary to track

Revision ID: a22937d2373
Revises: 18a9779b6cc1
Create Date: 2015-07-29 10:27:08.683007

"""

# revision identifiers, used by Alembic.
revision = 'a22937d2373'
down_revision = '18a9779b6cc1'

import fm  # noqa
import sqlalchemy as sa  # noqa

from alembic import op  # noqa
from fm.ext import db  # noqa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('audio_summary', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'audio_summary')
    ### end Alembic commands ###
